# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "REDACTED" # change this!
  limiter: true # can be disabled for a private instance
  image_proxy: true
engines:
  - name: brave
    disabled: false
  - name: qwant
    disabled: false
  - name: bing
    disabled: true
  - name: lingva
    disabled: true
  - name: translated
    disabled: true
  - name: wikidata
    disabled: true
  - name: bing_images
    disabled: true
  - name: artic
    disabled: true
  - name: deviantart
    disabled: true
  - name: loc
    disabled: true
  - name: wallhaven
    disabled: true
  - name: piratebay
    disabled: true
  - name: solidtorrents
    disabled: true
  - name: bt4g
    disabled: true
  - name: openverse
    disabled: true
  - name: kickass
    disabled: true
  - name: zlibrary
    disabled: true
  - name: lemmy
    disabled: true
  - name: mastodon
    disabled: true
  - name: tootfinder
    disabled: true
search:
  safe_search: 1
  autocomplete: "duckduckgo"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
